#!/bin/bash
#
# GITTED EXPORT: SYSCONF -> GIT files
#

. /usr/share/gitted/export.init.bash || exit 2

[ -z "$GITTED_DATA_PATH" ] && nef_fatal "missing variable: GITTED_DATA_PATH"

state_ref=$(gitted_state_ref_name sysconf)

if [ -d /sysconf/.git ]; then

    (
        local_git_dir=$GIT_DIR # local_git_dir is the path to "/local.repository.git"
        unset GIT_DIR
        unset GIT_WORK_TREE
        unset GIT_INDEX

        cd /sysconf

        # "$state_ref" in the /sysconf dir points to the commit that was
        # last merged into $local_git_dir
        if [ "$(git show-ref -s $state_ref)" != "$(git show-ref -s refs/heads/master)" ]; then

            nef_log "/sysconf head master has changed. Integrating back the changes..."

            # Clone a non-bare repository our of the central local one, to please git-subtree
            temp_branch=$(date +T%s)
            clone_path=/tmp/$temp_branch
            nef_log "Cloning $local_git_dir to: $clone_path[/.git]"
            nef_cmd -- mkdir $clone_path
            nef_cmd -- cp -a $local_git_dir $clone_path/.git
            cd $clone_path
            nef_cmd --log-prefix git-config -- git config --bool core.bare false
            nef_cmd --log-prefix git-symbolic-ref -- git symbolic-ref HEAD refs/heads/master
            nef_cmd --log-prefix git-readtree -- git read-tree HEAD
            nef_cmd --log-prefix git-checkout-index -- git checkout-index -u -a
            nef_log "Done cloning."

            nef_log "Executing: git subtree pull -P '$GITTED_DATA_PATH' /sysconf master"
            nef_cmd --log-prefix git-subtree -- git subtree pull -P $GITTED_DATA_PATH /sysconf master \
                -m "Automatic merge (git-subtree pull) by $0 on $(hostname)"
            nef_cmd --log-prefix git-push -- git push $local_git_dir master
            nef_log "Done pushing back the merge to: $local_git_dir <master>"

            cd /sysconf
            rm -rf $clone_path

            message="update after exporting sysconf (as a subtree) to the local repository"
            git update-ref -m "$message" $state_ref refs/heads/master

            cd $local_git_dir
            message="update after sysconf subtree merge"
            git update-ref -m "$message" $state_ref refs/heads/$GITTED_GIT_BRANCH $gitted_last_commit

        else
            nef_log "No change committed in /sysconf in branch master"
        fi

    ) || nef_fatal "sub-command failed"

else
    nef_log "/sysconf/.git does not exist, ignored."
fi
